# General Jekyll Config
pygments: true
url: http://blog.janbaer.de
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
markdown: kramdown

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#1B4D94'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: janbaer
    twitter: reabnaj
    google: +JanBaer

  # "Hi, I'm _______"
  name: Jan Baer
  email: jan@janbaer.de
  tagline: "Softwaredeveloper and -craftsman"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-6811781-2

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true
